alias gai='git add -i'
alias gap='git add -p'
alias gau='git add -u'
alias gca='git commit -a'
alias gcm='git commit --amend'
alias gcn='git commit --amend --no-edit'
alias gcp='git commit -p'
alias gd='git diff'
alias gdc='git diff --cached'
alias gm='git mergetool'
alias gp='git push origin HEAD'
alias gpf='gp -f'
alias gpr='git pull -r origin master'
alias grh='git reset HEAD --head'
alias gri='git rebase -i'
alias grs='git reset HEAD -- .' # reset staged
alias gs='git status -s'
# TODO: git cherry-pick -p A^..B
