#!/bin/sh
case "${SRANDRD_ACTION}" in
  "HDMI1 connected") source /home/rod/.screenlayout/gupy.sh;;
  "HDMI1 disconnected") source /home/rod/.screenlayout/default.sh;;
  *) echo "not found: ${SRANDRD_ACTION}";;
esac

