#!/bin/bash
FOREGROUND=$(xrdb -query | grep 'color15:'| awk 'NR==1{print $NF}')
#ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_full -m -1 -fullscreen 0 -theme-str "*{accent: ${FOREGROUND:-#000000};}")
ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_full -m -1 -fullscreen 0 -theme-str "*{accent: ${FOREGROUND:-#FFFFFF};}")

rofi "${ROFI_OPTIONS[@]}" -combi-modi window,drun,run -show combi
