#!/usr/bin/env bash

another=$(echo "LOCK
SUSPEND
LOGOUT
REBOOT
POWEROFF" | awk '{print $(NF-1)}' | trofi -dmenu -i -p "SYSTEM: ")

if [ "$another" == "LOCK" ] ; then
	i3exit lock;
elif [ "$another" == "SUSPEND" ] ; then
	i3exit suspend;
elif [ "$another" == "LOGOUT" ] ; then
	[ $(echo -e "Yes\nNo" | trofi -dmenu -i -p "Are you sure you want to proceed?") == Yes ] && i3exit exit
	
elif [ "$another" == "REBOOT" ] ; then
	[ $(echo -e "Yes\nNo" | trofi -dmenu -i -p "Are you sure you want to proceed?") == Yes ] && i3exit reboot
	
elif [ "$another" == "POWEROFF" ] ; then
	[ $(echo -e "Yes\nNo" | trofi -dmenu -i -p "Are you sure you want to proceed?") == Yes ] && i3exit poweroff

else
    echo $another
fi
