#!/bin/bash
cmd="@migration #update"
dunstify "$cmd" updating...

cd ~/dev/gupy/backend
git stash
git checkout master
git pull
./node_modules/.bin/sequelize db:migrate --url postgresql://postgres@localhost/gupy_development
./node_modules/.bin/sequelize db:migrate --url postgresql://postgres@localhost/gupy_test
git checkout -
if [[ $(git stash list | wc -l) -gt 0 ]]; then
  git stash pop
fi

if [[ "$?" -eq 0 ]]; then
  dunstify "$cmd" "done."
  tmux send -t migration ls ENTER
else
  dunstify "$cmd" "FAILED."
  urxvt -e tmux a -t migration &
fi

