#!/bin/bash
cmd="@migration #update"
dunstify -t 1000 "$cmd" updating...

cd ~/dev/gupy/backend/migrations
modified=$(git ls-files -m | wc -l)
if [[ "$modified" -gt 0 ]]; then git stash; fi
git checkout master
git pull
../node_modules/.bin/sequelize db:migrate --url postgresql://postgres@localhost/gupy_development
result=$?
../node_modules/.bin/sequelize db:migrate --url postgresql://postgres@localhost/gupy_test
git checkout -
if [[ "$modified" -gt 0 ]]; then git stash pop; fi

if [[ "$result" -eq 0 ]]; then
  dunstify "$cmd" "done."
  tmux send -t migration clear ENTER
else
  dunstify "$cmd" "FAILED."
  st -e zsh -i -c 'tmux a -t migration' &
fi

