#!/bin/bash

# One of the following: xrandr, xbacklight, kernel
METHOD="xbacklight"

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  xbacklight -inc 10
# Right click
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
  xbacklight -dec 10
fi

URGENT_VALUE=10

curBrightness=$(xbacklight -get)+0

if [[ "${curBrightness}" -le 0 ]]; then
  exit
fi

percent=$(echo "scale=0;${curBrightness}" | bc -l)

percent=${percent%.*}

if [[ "${percent}" -le 0 ]]; then
  exit
fi

echo "${percent}%"
echo "${percent}%"

if [[ "${percent}" -le "${URGENT_VALUE}" ]]; then
  exit 33
fi
