#!/usr/bin/env bash
if ! pgrep -x "" > /dev/null; then
  exit
fi
perc=$(transmission-remote -n transmission:transmission -l | awk '/Up & Down|Downloading/ {split($2,arr,"%"); tot += arr[1]; n += 1 } END { if(n>0) { print int(tot/n); } else { print "no"; }  }')
if [[ "${perc}" -ne "no" ]]; then
  echo "$perc%"
  echo "$perc%"
fi
